export const APP_URL = 'http://127.0.0.1:8000/api/v1/users';
export const LOGIN_URL = 'http://127.0.0.1:8000/api/v1/login';
export const LOGOUT_URL = 'http://127.0.0.1:8000/api/v1/logout';
export const URL_IMAGES = 'http://127.0.0.1:8000/images/';
export const GENDER_MALE = '0';
export const GENDER_FEMALE = '1';
export const DEACTIVED = 0;
export const ACTIVED = 1;
export const API_URL = 'http://127.0.0.1:8000/api/v1/';
export const PRODUCTS = 'products';
export const PRODUCT = 'product';
export const USERS = 'users';
export const USER = 'user';
export const USER_ADD = 'user/store';
export const TOKEN = sessionStorage.getItem('authentication') ? '?token='+JSON.parse(sessionStorage.getItem('authentication')).data.token : '';